# Local db config
  spring:
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/exam
      username: admin
      password: admin
      tomcat:
        validation-query: select 1 from dual
      hikari:
        connection-timeout: 5000
    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          ddl-auto: create
  mail:
    protocol: smtp
    host: smtp.turkcell.com.tr